### ISSUE TITLE
Cannot boot on my 15ARH05 with GTX 1650

### ISSUE THREAD

**Issue by D0lp1n** [833M0L3/Legion-4600H-Hackintosh#2]
Hey, I have the exact same laptop as you except that I have GTX 1650 instead of GTX 1650ti and 8gb of ram. I tried using this EFI but it fails. I suspect it is due to different BIOS device name of GTX 1650ti and GTX 1650 but I am not quite sure.
Here are the logs of failed boots.
[opencore-2023-09-12-145945.txt](https://github.com/833M0L3/Legion-4600H-Hackintosh/files/12586807/opencore-2023-09-12-145945.txt)
[opencore-2023-09-12-150022.txt](https://github.com/833M0L3/Legion-4600H-Hackintosh/files/12586809/opencore-2023-09-12-150022.txt)
Any help is appreciated!

**Comment by 833M0L3** [comment]
@D0lp1n  I recommend that to not use my EFI directly. Instead, look at it and try creating your own. The only thing you need to do is generate SSDT and modify your hardware serial number. Since kexts are already there, it will save you from trouble.

**Comment by D0lp1n** [comment]
Okay, will try making them on my own. Ty for the quick response!

**Comment by vladsendrix** [comment]
> Okay, will try making them on my own. Ty for the quick response!

Did you manage to boot, I generated my own SSDT and modified serial, still no luck yet.

**Comment by D0lp1n** [comment]
Nope it just does not work, I'm probably gonna make one from scratch later but I don't have the time right now, if you manage to boot tho lemme know!

**Comment by vladsendrix** [comment]
> Nope it just does not work, I'm probably gonna make one from scratch later but I don't have the time right now, if you manage to boot tho lemme know!

I'm starting work these next days on the stock 15arh05, here's the repo https://github.com/vladsendrix/15arh05. Will start work this weekend most likely.

**Comment by D0lp1n** [comment]
Just want to confirm before contributing, your Lenovo Legion 5 has Amd R5 4600H, Gtx 1650, 8gb of ram and on bios version EUCN39WW {15ARH05-Type:8B25}, right?

**Comment by vladsendrix** [comment]
> Just want to confirm before contributing, your Lenovo Legion 5 has Amd R5 4600H, Gtx 1650, 8gb of ram and on bios version EUCN39WW {15ARH05-Type:8B25}, right?

Yes, exactly the same specification.
