### ISSUE TITLE
question about compatibility for Sonoma

### ISSUE THREAD

**Issue by irfan-vora** [833M0L3/Legion-4600H-Hackintosh#5]
I am new to Hackintoshing but after some research I found that Opencore does not provide support to the AMD laptops. Despite that you have working hackintosh ventura. but I have a question that will it work on Sonoma? will all kexts work fine or not? I do want to try on Sonoma but if you've tried lemme know that it will work or not.

**Comment by chiksaaheksa** [comment]
Yes, it worked. however There are problems with Wi-Fi that can be fixed
