### ISSUE TITLE
GTX 1660ti

### ISSUE THREAD

**Issue by MostafaMohamed2002** [833M0L3/Legion-4600H-Hackintosh#6]
i have the same model as yours but with dGPU gtx1660ti will it work with my machine ?

**Comment by 833M0L3** [comment]
> I have the same model as yours but with dGPU gtx1660ti will it work with my machine?

@MostafaMohamed2002 , the guide and EFI shared here provide a foundation on how it can be done with Legion laptops. It's up to you to figure out how to make it happen. 

That said, Nvidia GPUs are completely disabled on this EFI of mine as it's not supported and cause trouble. Experiment with it, try building your EFI from scratch by following Dortania's guide, which I also did.
