### ISSUE TITLE
Battery Readouts Problem

### ISSUE THREAD

**Issue by irfan-vora** [833M0L3/Legion-4600H-Hackintosh#9]
Hey There!

I am having battery readout problem there is not showing battery indicator in status bar and in the system settings battery is showing fully charged all the time. I have the same model of laptop you have and I have used SMCBatteryManager.kext but it didn’t work. How do you fix the battery readout problem please help me! If you have done it by patching dsdt with rehabman’s way please send me the dsdt. Thank You.

**Comment by irfan-vora** [comment]
Hey Bro do you mind telling me how did you fix battery. 'Cause I tried everything except DSDT Patches.Please tell me how did you fix it.

**Comment by 833M0L3** [comment]
@irfan-vora  What do you mean by except for DSDT patches? Do you mean SSDT? Generate your own using SSDTTime, it's clearly written on the description

**Comment by irfan-vora** [comment]
Dsdt patches are for those laptops which has ec fields of more than 8bits and macOS only supports 8bits of EC so patch helps to convert those 16,32,64,128 bits to 8bits it is done by rehabman. 

And I have generated my own ssdts but no luck of battery status.You have only just created ssdts with ssdttime?

**Comment by 833M0L3** [comment]
@irfan-vora  Yes. I have only used SSDTs with SSDTIME

**Comment by irfan-vora** [comment]
@833M0L3 I have done the same and everything else is working but battery status won’t show

Edit:- What BIOS options do you disable and enable please tell me so I can regenrate SSDTs and check again if it works

**Comment by irfan-vora** [comment]
@833M0L3 Everything worked properly! Just used your efi and made some changes accordingly ssdts and usbmapping and smbios. To this prior I have generated my own EFI and I don’t know why it was causing problems I followed Dortania’s Opencore guide for zen desktops and a YT video from AKVAITHI. Since Battery status is working perfectly I am closing this issue
